---
- name: My Demo Playbook
  hosts: all
  become: true

  tasks:
  - name: Copy a file
    copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: rahul
