---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"


  - name: Installed apache2 package
    apt:
      name: apache2
      state: installed
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"


  - name: copy index.html
    copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /var/www/html
      mode: 0666

