---
- name: My Test Playbook
  hosts: webservers
  become: true
  tasks:
  - name: installed httpd package
    yum:
      name: httpd
      state: installed


  - name: Start httpd service
    service:
      name: httpd
      state: started
